<?php

namespace Go\Config;

/**
 * Test class for JsonConfig.
 * Generated by PHPUnit on 2011-10-17 at 13:28:50.
 */
class JsonConfigTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var JsonConfig
     */
    protected $object;

    /**
     * @var \Gaufrette\Filesystem
     */
    protected $filesystem;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->filesystem = new \Gaufrette\Filesystem(new \Gaufrette\Adapter\InMemory());
        $this->filesystem->write('config.json', file_get_contents(__DIR__.'/../../fixtures/config.json'));
        $this->object = new JsonConfig($this->filesystem->get('config.json'));
    }

    public function testConstruct()
    {
        $data = $this->object->getAll();
        $this->assertSame('bar', $data['foo']);
        $this->assertInternalType('array', $data['fool']);
        $this->assertSame('foo', $data['fool']['bar']);
    }

    public function testAdd()
    {
        $this->object->add(array(
            'foo' => 'barbar',
            'toto' => 'test'
        ));

        $data = $this->object->getAll();
        $this->assertSame('barbar', $data['foo']);
        $this->assertSame('test', $data['toto']);
        $this->assertInternalType('array', $data['fool']);
        $this->assertSame('foo', $data['fool']['bar']);
    }

    public function testSet()
    {
        $this->object->set('toto', 'titi');
        $this->object->set('test.titi', 'test');
        $this->object->set('test.tata.tutu', 'foobar');

        $data = $this->object->getAll();
        $this->assertSame('test', $data['test']['titi']);
        $this->assertSame('foobar', $data['test']['tata']['tutu']);
    }

    public function testGet()
    {
        $this->object->add(array(
            'foo' => 'barbar',
            'toto' => array(
                'titi' => 'test'
            )
        ));

        $this->assertSame('barbar', $this->object->get('foo'));
        $this->assertSame('test', $this->object->get('toto.titi'));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
?>
